# Generated by Django 4.2.25 on 2026-07-20 18:18

import core.fields
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individual', '0018_alter_groupindividual_role_and_more'),
        ('social_protection', '0014_replace_benefitplan_max_beneficiaries_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBeneficiaryChangeLog',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('operation', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=16)),
                ('source', models.CharField(choices=[('CSV_UPLOAD', 'CSV_UPLOAD'), ('CSV_UPDATE', 'CSV_UPDATE'), ('GRAPHQL', 'GRAPHQL'), ('ENROLLMENT', 'ENROLLMENT')], max_length=32)),
                ('code_menage', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('snapshot_before', models.JSONField(blank=True, default=dict, null=True)),
                ('snapshot_after', models.JSONField(blank=True, default=dict, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'PENDING'), ('QUEUED', 'QUEUED'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], db_index=True, default='PENDING', max_length=16)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.PositiveIntegerField(default=0)),
                ('sync_error', models.JSONField(blank=True, default=dict, null=True)),
                ('sync_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operator_response', models.JSONField(blank=True, default=dict, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beneficiary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='social_protection.beneficiary')),
                ('benefit_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='social_protection.benefitplan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='individual.individual')),
                ('upload_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='social_protection.benefitplandatauploadrecords')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical beneficiary change log',
                'verbose_name_plural': 'historical beneficiary change logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BeneficiaryChangeLog',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('operation', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=16)),
                ('source', models.CharField(choices=[('CSV_UPLOAD', 'CSV_UPLOAD'), ('CSV_UPDATE', 'CSV_UPDATE'), ('GRAPHQL', 'GRAPHQL'), ('ENROLLMENT', 'ENROLLMENT')], max_length=32)),
                ('code_menage', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('snapshot_before', models.JSONField(blank=True, default=dict, null=True)),
                ('snapshot_after', models.JSONField(blank=True, default=dict, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'PENDING'), ('QUEUED', 'QUEUED'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], db_index=True, default='PENDING', max_length=16)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.PositiveIntegerField(default=0)),
                ('sync_error', models.JSONField(blank=True, default=dict, null=True)),
                ('sync_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operator_response', models.JSONField(blank=True, default=dict, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='social_protection.beneficiary')),
                ('benefit_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='social_protection.benefitplan')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='individual.individual')),
                ('upload_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='social_protection.benefitplandatauploadrecords')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
